input {
file {
path => "/usr/share/logstash/pipeline/customers.csv"
start_position => "beginning"
sincedb_path => "/dev/null"
}
}
filter {
csv {
separator => ","
columns => ["CardHolderId","FirstName","LastName","Gender","ATMID","BirthDate","Occupation"]
}
}
output {
elasticsearch {
hosts => ["http://localhost:9200"]
index => "customers"
}
stdout {
codec => rubydebug
}
}