input {
file {
path => "/usr/share/logstash/pipeline/ventes.csv"
start_position => "beginning"
sincedb_path => "/dev/null"
}
}
filter {
csv {
separator => ","
columns => ["date","produit","ville","quantite","prix"]
}
}
output {
elasticsearch {
hosts => ["http://localhost:9200"]
index => "ventes"
}
stdout {
codec => rubydebug
}
}